#!/bin/bash

#### Webcamd Core Application.

#### crowsnest - A webcam Service for multiple Cams and Stream Services.
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2021
#### https://github.com/mainsail-crew/crowsnest
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces

# Exit upon Errors
set -Eex


CN_WORKDIR_PATH="$(dirname "$(readlink -f "${0}")")"
declare -r CN_WORKDIR_PATH

import_components() {
    find "${CN_WORKDIR_PATH}"/components -maxdepth 1 -not -name '.*' -prinf '%f '
}

main() {

    import_components

}

if [[ "${BASH_SOURCE[0]}" = "${0}" ]]; then
    main
fi
