#!/bin/bash

#### Crowsnest Core Application.

#### crowsnest - A webcam Service for multiple Cams and Stream Services.
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2021 - till today
#### https://github.com/mainsail-crew/crowsnest
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces

# Exit upon Errors
set -Eex


CN_WORKDIR_PATH="$(dirname "$(readlink -f "${0}")")"
declare -r CN_WORKDIR_PATH

cn_import_components() {
    local -a components
    local files
    files="$(find "${CN_WORKDIR_PATH}/components/" -type f -not -name '.*' -printf '%f\n')"

    for file in ${files}; do
        components+=("${file}")
    done

    for component in "${components[@]}"; do
        # shellcheck disable=SC1090
        . "${CN_WORKDIR_PATH}"/components/"${component}"
    done
}

main() {

    cn_import_components

    cn_init_traps

    echo "${@}"
}

if [[ "${BASH_SOURCE[0]}" = "${0}" ]]; then
    main "${@}" | tee >> "${CN_WORKDIR_PATH}/test.log"
fi
